name: Process Images

on:
  push:
    paths:
      - '**.jpg'
      - '**.png'

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Pillow
      run: pip install Pillow
    
    - name: Run script to process images
      run: python process_images.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'Ignacio Olmedo'
        git config --global user.email 'iolmedo@filadd.com'
        git add .
        git commit -m "Optimizar imágenes"
        git push
